sudo: false
dist: trusty
language: node_js
node_js:
  - "stable"
  - "8"
  - "7"
  - "6"
cache:
  yarn: true
  directories:
    - "node_modules"

script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && codecov
  - codecov
  - yarn test
