const LoremSentences = [
  [
    { type: 'sentence', content: 'Lorem ipsum dolor sit amet' },
    { type: 'comma' },
    { type: 'sentence', content: 'consectetur adipiscing elit' },
    { type: 'period' },
    { type: 'sentence', content: 'Mauris eleifend rutrum turpis at bibendum' },
    { type: 'period' },
    { type: 'sentence', content: 'Proin viverra lobortis lorem' },
    { type: 'comma' },
    { type: 'sentence', content: 'ut scelerisque tortor pharetra id' },
    { type: 'period' },
    { type: 'sentence', content: 'Proin lacinia orci justo' },
    { type: 'comma' },
    { type: 'sentence', content: 'nec semper diam commodo sed' },
    { type: 'period' },
    { type: 'sentence', content: 'In iaculis sodales tellus pulvinar posuere' },
    { type: 'period' },
    { type: 'sentence', content: 'Sed in mi et augue tristique maximus' },
    { type: 'period' },
    { type: 'sentence', content: 'Vivamus vitae diam vitae odio malesuada dignissim vel vel leo' },
    { type: 'period' },
    { type: 'sentence', content: 'Etiam accumsan mauris ac suscipit lacinia' },
    { type: 'period' }
  ],
  [
    { type: 'sentence', content: 'Suspendisse ultrices condimentum massa sit amet consectetur' },
    { type: 'period' },
    { type: 'sentence', content: 'Integer bibendum elementum dapibus' },
    { type: 'period' },
    { type: 'sentence', content: 'Maecenas eget fermentum lacus' },
    { type: 'period' },
    { type: 'sentence', content: 'Ut vitae volutpat sem' },
    { type: 'period' },
    { type: 'sentence', content: 'Nullam et justo a ante aliquam tincidunt quis ut leo' },
    { type: 'period' },
    { type: 'sentence', content: 'Fusce dignissim arcu ex' },
    { type: 'comma' },
    { type: 'sentence', content: 'nec imperdiet ante interdum id' },
    { type: 'period' },
    { type: 'sentence', content: 'Aliquam erat volutpat' },
    { type: 'period' },
    { type: 'sentence', content: 'Aliquam semper consectetur eros id tempus' },
    { type: 'period' },
    { type: 'sentence', content: 'Vivamus gravida enim quis sapien finibus' },
    { type: 'comma' },
    { type: 'sentence', content: 'pharetra sollicitudin enim venenatis' },
    { type: 'period' },
    { type: 'sentence', content: 'Cras feugiat porttitor lectus' },
    { type: 'comma' },
    { type: 'sentence', content: 'sit amet gravida magna semper non' },
    { type: 'period' },
    { type: 'sentence', content: 'Fusce tristique mi eget ex convallis' },
    { type: 'comma' },
    { type: 'sentence', content: 'a pellentesque velit dictum' },
    { type: 'period' },
    { type: 'sentence', content: 'Mauris bibendum vitae massa et tristique' },
    { type: 'period' },
    { type: 'sentence', content: 'Praesent iaculis ornare lacus' },
    { type: 'comma' },
    { type: 'sentence', content: 'id commodo nulla efficitur quis' },
    { type: 'period' }
  ],
  [
    { type: 'sentence', content: 'Mauris varius metus justo' },
    { type: 'comma' },
    { type: 'sentence', content: 'at fermentum nibh sagittis at' },
    { type: 'period' },
    { type: 'sentence', content: 'Maecenas pharetra eu orci iaculis dictum' },
    { type: 'period' },
    { type: 'sentence', content: 'Phasellus hendrerit' },
    { type: 'comma' },
    { type: 'sentence', content: 'mi eget dictum tincidunt' },
    { type: 'comma' },
    { type: 'sentence', content: 'dolor quam molestie diam' },
    { type: 'comma' },
    { type: 'sentence', content: 'a laoreet diam nisl at mauris' },
    { type: 'period' },
    { type: 'sentence', content: 'Curabitur convallis euismod semper' },
    { type: 'period' },
    { type: 'sentence', content: 'Aliquam elementum odio neque' },
    { type: 'comma' },
    { type: 'sentence', content: 'non vestibulum augue ultricies nec' },
    { type: 'period' },
    { type: 'sentence', content: 'Sed ornare tellus ac nulla efficitur sagittis' },
    { type: 'period' },
    { type: 'sentence', content: 'Class aptent taciti sociosqu ad litora torquent per conubia nostra' },
    { type: 'comma' },
    { type: 'sentence', content: 'per inceptos himenaeos' },
    { type: 'period' },
    { type: 'sentence', content: 'Sed malesuada justo est' },
    { type: 'comma' },
    { type: 'sentence', content: 'in varius turpis malesuada eget' },
    { type: 'period' },
    { type: 'sentence', content: 'Proin tempus' },
    { type: 'comma' },
    { type: 'sentence', content: 'mi nec lobortis ultricies' },
    { type: 'comma' },
    { type: 'sentence', content: 'arcu nisi interdum lectus' },
    { type: 'comma' },
    { type: 'sentence', content: 'sed scelerisque nulla massa sed massa' },
    { type: 'period' },
    { type: 'sentence', content: 'Donec maximus augue at dui consequat fermentum' },
    { type: 'period' },
    { type: 'sentence', content: 'Aliquam erat volutpat' },
    { type: 'period' },
    { type: 'sentence', content: 'Aenean risus nisl' },
    { type: 'comma' },
    { type: 'sentence', content: 'facilisis in dolor a' },
    { type: 'comma' },
    { type: 'sentence', content: 'aliquet pellentesque augue' },
    { type: 'period' },
    { type: 'sentence', content: 'Nulla vitae eros rhoncus sem viverra pulvinar' },
    { type: 'period' },
    { type: 'sentence', content: 'Aliquam consequat eleifend tortor' },
    { type: 'comma' },
    { type: 'sentence', content: 'non convallis tortor laoreet id' },
    { type: 'period' },
    { type: 'sentence', content: 'Cras posuere metus non ipsum hendrerit lacinia' },
    { type: 'period' }
  ],
  [
    { type: 'sentence', content: 'Nam vestibulum erat justo' },
    { type: 'comma' },
    { type: 'sentence', content: 'ac posuere ipsum aliquet a' },
    { type: 'period' },
    { type: 'sentence', content: 'Etiam in efficitur felis' },
    { type: 'period' },
    { type: 'sentence', content: 'Suspendisse potenti' },
    { type: 'period' },
    { type: 'sentence', content: 'Aliquam iaculis erat sit amet lorem euismod' },
    { type: 'comma' },
    { type: 'sentence', content: 'eu placerat tellus maximus' },
    { type: 'period' },
    { type: 'sentence', content: 'Sed rutrum tellus eu rhoncus iaculis' },
    { type: 'period' },
    { type: 'sentence', content: 'Proin pretium quam in justo gravida' },
    { type: 'comma' },
    { type: 'sentence', content: 'in tempor leo viverra' },
    { type: 'period' },
    { type: 'sentence', content: 'Aenean metus lectus' },
    { type: 'comma' },
    { type: 'sentence', content: 'tincidunt at tempor a' },
    { type: 'comma' },
    { type: 'sentence', content: 'maximus consequat lorem' },
    { type: 'period' },
    { type: 'sentence', content: 'Sed dictum eros urna' },
    { type: 'comma' },
    { type: 'sentence', content: 'a tristique nisi placerat sit amet' },
    { type: 'period' },
    { type: 'sentence', content: 'Proin in augue eu lectus facilisis finibus ut placerat velit' },
    { type: 'period' },
    { type: 'sentence', content: 'Aliquam sapien ex' },
    { type: 'comma' },
    { type: 'sentence', content: 'consequat id arcu eu' },
    { type: 'comma' },
    { type: 'sentence', content: 'facilisis suscipit turpis' },
    { type: 'period' }
  ],
  [
    { type: 'sentence', content: 'Morbi id mollis leo' },
    { type: 'period' },
    { type: 'sentence', content: 'Morbi sed nisl ut felis aliquam auctor quis ac leo' },
    { type: 'period' },
    { type: 'sentence', content: 'Phasellus consequat dolor eget purus dignissim' },
    { type: 'comma' },
    { type: 'sentence', content: 'eget rutrum augue varius' },
    { type: 'period' },
    { type: 'sentence', content: 'Nullam cursus mollis odio id tempor' },
    { type: 'period' },
    { type: 'sentence', content: 'Donec quis dapibus justo' },
    { type: 'comma' },
    { type: 'sentence', content: 'convallis fermentum eros' },
    { type: 'period' },
    { type: 'sentence', content: 'Cras volutpat mattis semper' },
    { type: 'period' },
    { type: 'sentence', content: 'Fusce bibendum sollicitudin libero' },
    { type: 'comma' },
    { type: 'sentence', content: 'quis commodo felis varius eu' },
    { type: 'period' },
    { type: 'sentence', content: 'Vestibulum congue viverra massa sed commodo' },
    { type: 'period' },
    { type: 'sentence', content: 'Duis auctor interdum orci' },
    { type: 'comma' },
    { type: 'sentence', content: 'at iaculis dui' },
    { type: 'period' },
    { type: 'sentence', content: 'Etiam orci turpis' },
    { type: 'comma' },
    { type: 'sentence', content: 'mattis et est ac' },
    { type: 'comma' },
    { type: 'sentence', content: 'maximus posuere ligula' },
    { type: 'period' },
    { type: 'sentence', content: 'Pellentesque sit amet maximus orci' },
    { type: 'period' },
    { type: 'sentence', content: 'In hac habitasse platea dictumst' },
    { type: 'period' },
    { type: 'sentence', content: 'Etiam sit amet nunc porta lectus consequat auctor sagittis fringilla enim' },
    { type: 'period' }
  ]
];

LoremSentences.Sentences =
  LoremSentences
    .reduce((acc, paragraph) => [...acc, ...paragraph], [])
    .filter(token => token.type === 'sentence')
    .map(token => token.content);

export default LoremSentences;
