const comma = { type: 'comma' };
const period = { type: 'period' };
const sentence = (content) => ({ type: 'sentence', content });

const LoremSentences = [
  [
    sentence('Lorem ipsum dolor sit amet'),
    comma,
    sentence('consectetur adipiscing elit'),
    period,
    sentence('Mauris eleifend rutrum turpis at bibendum'),
    period,
    sentence('Proin viverra lobortis lorem'),
    comma,
    sentence('ut scelerisque tortor pharetra id'),
    period,
    sentence('Proin lacinia orci justo'),
    comma,
    sentence('nec semper diam commodo sed'),
    period,
    sentence('In iaculis sodales tellus pulvinar posuere'),
    period,
    sentence('Sed in mi et augue tristique maximus'),
    period,
    sentence('Vivamus vitae diam vitae odio malesuada dignissim vel vel leo'),
    period,
    sentence('Etiam accumsan mauris ac suscipit lacinia'),
    period
  ],
  [
    sentence('Suspendisse ultrices condimentum massa sit amet consectetur'),
    period,
    sentence('Integer bibendum elementum dapibus'),
    period,
    sentence('Maecenas eget fermentum lacus'),
    period,
    sentence('Ut vitae volutpat sem'),
    period,
    sentence('Nullam et justo a ante aliquam tincidunt quis ut leo'),
    period,
    sentence('Fusce dignissim arcu ex'),
    comma,
    sentence('nec imperdiet ante interdum id'),
    period,
    sentence('Aliquam erat volutpat'),
    period,
    sentence('Aliquam semper consectetur eros id tempus'),
    period,
    sentence('Vivamus gravida enim quis sapien finibus'),
    comma,
    sentence('pharetra sollicitudin enim venenatis'),
    period,
    sentence('Cras feugiat porttitor lectus'),
    comma,
    sentence('sit amet gravida magna semper non'),
    period,
    sentence('Fusce tristique mi eget ex convallis'),
    comma,
    sentence('a pellentesque velit dictum'),
    period,
    sentence('Mauris bibendum vitae massa et tristique'),
    period,
    sentence('Praesent iaculis ornare lacus'),
    comma,
    sentence('id commodo nulla efficitur quis'),
    period
  ],
  [
    sentence('Mauris varius metus justo'),
    comma,
    sentence('at fermentum nibh sagittis at'),
    period,
    sentence('Maecenas pharetra eu orci iaculis dictum'),
    period,
    sentence('Phasellus hendrerit'),
    comma,
    sentence('mi eget dictum tincidunt'),
    comma,
    sentence('dolor quam molestie diam'),
    comma,
    sentence('a laoreet diam nisl at mauris'),
    period,
    sentence('Curabitur convallis euismod semper'),
    period,
    sentence('Aliquam elementum odio neque'),
    comma,
    sentence('non vestibulum augue ultricies nec'),
    period,
    sentence('Sed ornare tellus ac nulla efficitur sagittis'),
    period,
    sentence('Class aptent taciti sociosqu ad litora torquent per conubia nostra'),
    comma,
    sentence('per inceptos himenaeos'),
    period,
    sentence('Sed malesuada justo est'),
    comma,
    sentence('in varius turpis malesuada eget'),
    period,
    sentence('Proin tempus'),
    comma,
    sentence('mi nec lobortis ultricies'),
    comma,
    sentence('arcu nisi interdum lectus'),
    comma,
    sentence('sed scelerisque nulla massa sed massa'),
    period,
    sentence('Donec maximus augue at dui consequat fermentum'),
    period,
    sentence('Aliquam erat volutpat'),
    period,
    sentence('Aenean risus nisl'),
    comma,
    sentence('facilisis in dolor a'),
    comma,
    sentence('aliquet pellentesque augue'),
    period,
    sentence('Nulla vitae eros rhoncus sem viverra pulvinar'),
    period,
    sentence('Aliquam consequat eleifend tortor'),
    comma,
    sentence('non convallis tortor laoreet id'),
    period,
    sentence('Cras posuere metus non ipsum hendrerit lacinia'),
    period
  ],
  [
    sentence('Nam vestibulum erat justo'),
    comma,
    sentence('ac posuere ipsum aliquet a'),
    period,
    sentence('Etiam in efficitur felis'),
    period,
    sentence('Suspendisse potenti'),
    period,
    sentence('Aliquam iaculis erat sit amet lorem euismod'),
    comma,
    sentence('eu placerat tellus maximus'),
    period,
    sentence('Sed rutrum tellus eu rhoncus iaculis'),
    period,
    sentence('Proin pretium quam in justo gravida'),
    comma,
    sentence('in tempor leo viverra'),
    period,
    sentence('Aenean metus lectus'),
    comma,
    sentence('tincidunt at tempor a'),
    comma,
    sentence('maximus consequat lorem'),
    period,
    sentence('Sed dictum eros urna'),
    comma,
    sentence('a tristique nisi placerat sit amet'),
    period,
    sentence('Proin in augue eu lectus facilisis finibus ut placerat velit'),
    period,
    sentence('Aliquam sapien ex'),
    comma,
    sentence('consequat id arcu eu'),
    comma,
    sentence('facilisis suscipit turpis'),
    period
  ],
  [
    sentence('Morbi id mollis leo'),
    period,
    sentence('Morbi sed nisl ut felis aliquam auctor quis ac leo'),
    period,
    sentence('Phasellus consequat dolor eget purus dignissim'),
    comma,
    sentence('eget rutrum augue varius'),
    period,
    sentence('Nullam cursus mollis odio id tempor'),
    period,
    sentence('Donec quis dapibus justo'),
    comma,
    sentence('convallis fermentum eros'),
    period,
    sentence('Cras volutpat mattis semper'),
    period,
    sentence('Fusce bibendum sollicitudin libero'),
    comma,
    sentence('quis commodo felis varius eu'),
    period,
    sentence('Vestibulum congue viverra massa sed commodo'),
    period,
    sentence('Duis auctor interdum orci'),
    comma,
    sentence('at iaculis dui'),
    period,
    sentence('Etiam orci turpis'),
    comma,
    sentence('mattis et est ac'),
    comma,
    sentence('maximus posuere ligula'),
    period,
    sentence('Pellentesque sit amet maximus orci'),
    period,
    sentence('In hac habitasse platea dictumst'),
    period,
    sentence('Etiam sit amet nunc porta lectus consequat auctor sagittis fringilla enim'),
    period
  ]
];

Object.defineProperty(LoremSentences, 'Sentences', {
  get: () => LoremSentences
    .reduce((acc, paragraph) => [...acc, ...paragraph], [])
    .filter(token => token.type === 'sentence')
    .map(token => token.content)
});

export default LoremSentences;
