const LoremWords = [
  [
    { type: 'word', content: 'Lorem' },
    { type: 'word', content: 'ipsum' },
    { type: 'word', content: 'dolor' },
    { type: 'word', content: 'sit' },
    { type: 'word', content: 'amet' },
    { type: 'comma' },
    { type: 'word', content: 'consectetur' },
    { type: 'word', content: 'adipiscing' },
    { type: 'word', content: 'elit' },
    { type: 'period' },
    { type: 'word', content: 'Mauris' },
    { type: 'word', content: 'laoreet' },
    { type: 'word', content: 'vulputate' },
    { type: 'word', content: 'sem' },
    { type: 'word', content: 'in' },
    { type: 'word', content: 'congue' },
    { type: 'period' },
    { type: 'word', content: 'Nunc' },
    { type: 'word', content: 'ut' },
    { type: 'word', content: 'porttitor' },
    { type: 'word', content: 'ligula' },
    { type: 'comma' },
    { type: 'word', content: 'eu' },
    { type: 'word', content: 'fringilla' },
    { type: 'word', content: 'augue' },
    { type: 'period' },
    { type: 'word', content: 'Vivamus' },
    { type: 'word', content: 'diam' },
    { type: 'word', content: 'nisl' },
    { type: 'comma' },
    { type: 'word', content: 'ultricies' },
    { type: 'word', content: 'nec' },
    { type: 'word', content: 'tortor' },
    { type: 'word', content: 'non' },
    { type: 'comma' },
    { type: 'word', content: 'efficitur' },
    { type: 'word', content: 'euismod' },
    { type: 'word', content: 'nulla' },
    { type: 'period' },
    { type: 'word', content: 'In' },
    { type: 'word', content: 'hac' },
    { type: 'word', content: 'habitasse' },
    { type: 'word', content: 'platea' },
    { type: 'word', content: 'dictumst' },
    { type: 'period' },
    { type: 'word', content: 'Pellentesque' },
    { type: 'word', content: 'tortor' },
    { type: 'word', content: 'nunc' },
    { type: 'comma' },
    { type: 'word', content: 'dictum' },
    { type: 'word', content: 'vel' },
    { type: 'word', content: 'mollis' },
    { type: 'word', content: 'a' },
    { type: 'comma' },
    { type: 'word', content: 'pretium' },
    { type: 'word', content: 'nec' },
    { type: 'word', content: 'lorem' },
    { type: 'period' },
    { type: 'word', content: 'Duis' },
    { type: 'word', content: 'vitae' },
    { type: 'word', content: 'arcu' },
    { type: 'word', content: 'nec' },
    { type: 'word', content: 'sapien' },
    { type: 'word', content: 'commodo' },
    { type: 'word', content: 'fermentum' },
    { type: 'period' },
    { type: 'word', content: 'Sed' },
    { type: 'word', content: 'aliquet' },
    { type: 'word', content: 'erat' },
    { type: 'word', content: 'lacus' },
    { type: 'comma' },
    { type: 'word', content: 'vitae' },
    { type: 'word', content: 'imperdiet' },
    { type: 'word', content: 'quam' },
    { type: 'word', content: 'sodales' },
    { type: 'word', content: 'ac' },
    { type: 'period' },
    { type: 'word', content: 'Aenean' },
    { type: 'word', content: 'ex' },
    { type: 'word', content: 'diam' },
    { type: 'comma' },
    { type: 'word', content: 'porttitor' },
    { type: 'word', content: 'eu' },
    { type: 'word', content: 'mi' },
    { type: 'word', content: 'eget' },
    { type: 'comma' },
    { type: 'word', content: 'ullamcorper' },
    { type: 'word', content: 'facilisis' },
    { type: 'word', content: 'mauris' },
    { type: 'period' },
    { type: 'word', content: 'Nulla' },
    { type: 'word', content: 'commodo' },
    { type: 'word', content: 'sed' },
    { type: 'word', content: 'sem' },
    { type: 'word', content: 'et' },
    { type: 'word', content: 'molestie' },
    { type: 'period' }
  ],
  [
    { type: 'word', content: 'Phasellus' },
    { type: 'word', content: 'placerat' },
    { type: 'comma' },
    { type: 'word', content: 'nibh' },
    { type: 'word', content: 'ut' },
    { type: 'word', content: 'dictum' },
    { type: 'word', content: 'placerat' },
    { type: 'comma' },
    { type: 'word', content: 'nibh' },
    { type: 'word', content: 'augue' },
    { type: 'word', content: 'feugiat' },
    { type: 'word', content: 'urna' },
    { type: 'comma' },
    { type: 'word', content: 'quis' },
    { type: 'word', content: 'rutrum' },
    { type: 'word', content: 'est' },
    { type: 'word', content: 'arcu' },
    { type: 'word', content: 'non' },
    { type: 'word', content: 'ligula' },
    { type: 'period' },
    { type: 'word', content: 'Aenean' },
    { type: 'word', content: 'elementum' },
    { type: 'comma' },
    { type: 'word', content: 'eros' },
    { type: 'word', content: 'eget' },
    { type: 'word', content: 'iaculis' },
    { type: 'word', content: 'eleifend' },
    { type: 'comma' },
    { type: 'word', content: 'massa' },
    { type: 'word', content: 'dolor' },
    { type: 'word', content: 'tempor' },
    { type: 'word', content: 'nulla' },
    { type: 'comma' },
    { type: 'word', content: 'eu' },
    { type: 'word', content: 'auctor' },
    { type: 'word', content: 'felis' },
    { type: 'word', content: 'lorem' },
    { type: 'word', content: 'at' },
    { type: 'word', content: 'lectus' },
    { type: 'period' },
    { type: 'word', content: 'Duis' },
    { type: 'word', content: 'vitae' },
    { type: 'word', content: 'efficitur' },
    { type: 'word', content: 'dui' },
    { type: 'period' },
    { type: 'word', content: 'Fusce' },
    { type: 'word', content: 'ut' },
    { type: 'word', content: 'dolor' },
    { type: 'word', content: 'orci' },
    { type: 'period' },
    { type: 'word', content: 'Donec' },
    { type: 'word', content: 'mattis' },
    { type: 'word', content: 'quis' },
    { type: 'word', content: 'lacus' },
    { type: 'word', content: 'in' },
    { type: 'word', content: 'sagittis' },
    { type: 'period' },
    { type: 'word', content: 'Pellentesque' },
    { type: 'word', content: 'porttitor' },
    { type: 'word', content: 'congue' },
    { type: 'word', content: 'metus' },
    { type: 'comma' },
    { type: 'word', content: 'sit' },
    { type: 'word', content: 'amet' },
    { type: 'word', content: 'ultrices' },
    { type: 'word', content: 'lectus' },
    { type: 'word', content: 'pellentesque' },
    { type: 'word', content: 'id' },
    { type: 'period' },
    { type: 'word', content: 'Ut' },
    { type: 'word', content: 'consectetur' },
    { type: 'word', content: 'vitae' },
    { type: 'word', content: 'purus' },
    { type: 'word', content: 'vitae' },
    { type: 'word', content: 'luctus' },
    { type: 'period' },
    { type: 'word', content: 'Aenean' },
    { type: 'word', content: 'sed' },
    { type: 'word', content: 'arcu' },
    { type: 'word', content: 'sem' },
    { type: 'period' },
    { type: 'word', content: 'Nam' },
    { type: 'word', content: 'interdum' },
    { type: 'comma' },
    { type: 'word', content: 'ante' },
    { type: 'word', content: 'a' },
    { type: 'word', content: 'lobortis' },
    { type: 'word', content: 'fringilla' },
    { type: 'comma' },
    { type: 'word', content: 'ipsum' },
    { type: 'word', content: 'diam' },
    { type: 'word', content: 'pharetra' },
    { type: 'word', content: 'magna' },
    { type: 'comma' },
    { type: 'word', content: 'nec' },
    { type: 'word', content: 'dictum' },
    { type: 'word', content: 'mauris' },
    { type: 'word', content: 'felis' },
    { type: 'word', content: 'a' },
    { type: 'word', content: 'mi' },
    { type: 'period' },
    { type: 'word', content: 'Aenean' },
    { type: 'word', content: 'ac' },
    { type: 'word', content: 'libero' },
    { type: 'word', content: 'sed' },
    { type: 'word', content: 'dui' },
    { type: 'word', content: 'elementum' },
    { type: 'word', content: 'accumsan' },
    { type: 'period' },
    { type: 'word', content: 'Aliquam' },
    { type: 'word', content: 'at' },
    { type: 'word', content: 'odio' },
    { type: 'word', content: 'congue' },
    { type: 'comma' },
    { type: 'word', content: 'faucibus' },
    { type: 'word', content: 'ante' },
    { type: 'word', content: 'vitae' },
    { type: 'comma' },
    { type: 'word', content: 'hendrerit' },
    { type: 'word', content: 'orci' },
    { type: 'period' },
    { type: 'word', content: 'Proin' },
    { type: 'word', content: 'sit' },
    { type: 'word', content: 'amet' },
    { type: 'word', content: 'arcu' },
    { type: 'word', content: 'non' },
    { type: 'word', content: 'felis' },
    { type: 'word', content: 'volutpat' },
    { type: 'word', content: 'tristique' },
    { type: 'word', content: 'id' },
    { type: 'word', content: 'vitae' },
    { type: 'word', content: 'ex' },
    { type: 'period' },
    { type: 'word', content: 'In' },
    { type: 'word', content: 'hac' },
    { type: 'word', content: 'habitasse' },
    { type: 'word', content: 'platea' },
    { type: 'word', content: 'dictumst' },
    { type: 'period' }
  ],
  [
    { type: 'word', content: 'Lorem' },
    { type: 'word', content: 'ipsum' },
    { type: 'word', content: 'dolor' },
    { type: 'word', content: 'sit' },
    { type: 'word', content: 'amet' },
    { type: 'comma' },
    { type: 'word', content: 'consectetur' },
    { type: 'word', content: 'adipiscing' },
    { type: 'word', content: 'elit' },
    { type: 'period' },
    { type: 'word', content: 'Phasellus' },
    { type: 'word', content: 'mollis' },
    { type: 'word', content: 'posuere' },
    { type: 'word', content: 'elit' },
    { type: 'period' },
    { type: 'word', content: 'Curabitur' },
    { type: 'word', content: 'bibendum' },
    { type: 'word', content: 'felis' },
    { type: 'word', content: 'a' },
    { type: 'word', content: 'turpis' },
    { type: 'word', content: 'rutrum' },
    { type: 'comma' },
    { type: 'word', content: 'nec' },
    { type: 'word', content: 'sodales' },
    { type: 'word', content: 'sem' },
    { type: 'word', content: 'dapibus' },
    { type: 'period' },
    { type: 'word', content: 'Sed' },
    { type: 'word', content: 'ac' },
    { type: 'word', content: 'egestas' },
    { type: 'word', content: 'ante' },
    { type: 'period' },
    { type: 'word', content: 'Quisque' },
    { type: 'word', content: 'pellentesque' },
    { type: 'word', content: 'mi' },
    { type: 'word', content: 'a' },
    { type: 'word', content: 'quam' },
    { type: 'word', content: 'lacinia' },
    { type: 'comma' },
    { type: 'word', content: 'ac' },
    { type: 'word', content: 'tristique' },
    { type: 'word', content: 'leo' },
    { type: 'word', content: 'ultricies' },
    { type: 'period' },
    { type: 'word', content: 'Nunc' },
    { type: 'word', content: 'nec' },
    { type: 'word', content: 'luctus' },
    { type: 'word', content: 'felis' },
    { type: 'period' },
    { type: 'word', content: 'Integer' },
    { type: 'word', content: 'sapien' },
    { type: 'word', content: 'ante' },
    { type: 'comma' },
    { type: 'word', content: 'mattis' },
    { type: 'word', content: 'in' },
    { type: 'word', content: 'nunc' },
    { type: 'word', content: 'vitae' },
    { type: 'comma' },
    { type: 'word', content: 'consectetur' },
    { type: 'word', content: 'sollicitudin' },
    { type: 'word', content: 'tortor' },
    { type: 'period' },
    { type: 'word', content: 'Sed' },
    { type: 'word', content: 'fringilla' },
    { type: 'word', content: 'augue' },
    { type: 'word', content: 'lacus' },
    { type: 'comma' },
    { type: 'word', content: 'ac' },
    { type: 'word', content: 'lacinia' },
    { type: 'word', content: 'mauris' },
    { type: 'word', content: 'volutpat' },
    { type: 'word', content: 'eu' },
    { type: 'period' },
    { type: 'word', content: 'Morbi' },
    { type: 'word', content: 'interdum' },
    { type: 'word', content: 'erat' },
    { type: 'word', content: 'eu' },
    { type: 'word', content: 'lectus' },
    { type: 'word', content: 'eleifend' },
    { type: 'comma' },
    { type: 'word', content: 'sit' },
    { type: 'word', content: 'amet' },
    { type: 'word', content: 'venenatis' },
    { type: 'word', content: 'mauris' },
    { type: 'word', content: 'gravida' },
    { type: 'period' }
  ],
  [
    { type: 'word', content: 'Vivamus' },
    { type: 'word', content: 'condimentum' },
    { type: 'word', content: 'dui' },
    { type: 'word', content: 'non' },
    { type: 'word', content: 'velit' },
    { type: 'word', content: 'pulvinar' },
    { type: 'comma' },
    { type: 'word', content: 'ac' },
    { type: 'word', content: 'molestie' },
    { type: 'word', content: 'justo' },
    { type: 'word', content: 'porttitor' },
    { type: 'period' },
    { type: 'word', content: 'Nulla' },
    { type: 'word', content: 'vel' },
    { type: 'word', content: 'aliquam' },
    { type: 'word', content: 'eros' },
    { type: 'period' },
    { type: 'word', content: 'Vivamus' },
    { type: 'word', content: 'vulputate' },
    { type: 'comma' },
    { type: 'word', content: 'nisl' },
    { type: 'word', content: 'at' },
    { type: 'word', content: 'bibendum' },
    { type: 'word', content: 'bibendum' },
    { type: 'comma' },
    { type: 'word', content: 'elit' },
    { type: 'word', content: 'lorem' },
    { type: 'word', content: 'eleifend' },
    { type: 'word', content: 'massa' },
    { type: 'comma' },
    { type: 'word', content: 'nec' },
    { type: 'word', content: 'finibus' },
    { type: 'word', content: 'ipsum' },
    { type: 'word', content: 'ipsum' },
    { type: 'word', content: 'in' },
    { type: 'word', content: 'velit' },
    { type: 'period' },
    { type: 'word', content: 'In' },
    { type: 'word', content: 'non' },
    { type: 'word', content: 'dui' },
    { type: 'word', content: 'quis' },
    { type: 'word', content: 'lorem' },
    { type: 'word', content: 'mattis' },
    { type: 'word', content: 'vulputate' },
    { type: 'word', content: 'a' },
    { type: 'word', content: 'ac' },
    { type: 'word', content: 'lacus' },
    { type: 'period' },
    { type: 'word', content: 'Curabitur' },
    { type: 'word', content: 'sed' },
    { type: 'word', content: 'neque' },
    { type: 'word', content: 'velit' },
    { type: 'period' },
    { type: 'word', content: 'Nulla' },
    { type: 'word', content: 'volutpat' },
    { type: 'word', content: 'turpis' },
    { type: 'word', content: 'eget' },
    { type: 'word', content: 'justo' },
    { type: 'word', content: 'tempor' },
    { type: 'word', content: 'porta' },
    { type: 'period' },
    { type: 'word', content: 'Pellentesque' },
    { type: 'word', content: 'risus' },
    { type: 'word', content: 'nisl' },
    { type: 'comma' },
    { type: 'word', content: 'semper' },
    { type: 'word', content: 'at' },
    { type: 'word', content: 'dolor' },
    { type: 'word', content: 'sed' },
    { type: 'comma' },
    { type: 'word', content: 'ornare' },
    { type: 'word', content: 'molestie' },
    { type: 'word', content: 'metus' },
    { type: 'period' },
    { type: 'word', content: 'Aliquam' },
    { type: 'word', content: 'ut' },
    { type: 'word', content: 'nisl' },
    { type: 'word', content: 'ut' },
    { type: 'word', content: 'nulla' },
    { type: 'word', content: 'rhoncus' },
    { type: 'word', content: 'blandit' },
    { type: 'word', content: 'quis' },
    { type: 'word', content: 'at' },
    { type: 'word', content: 'turpis' },
    { type: 'period' },
    { type: 'word', content: 'Nunc' },
    { type: 'word', content: 'condimentum' },
    { type: 'comma' },
    { type: 'word', content: 'nulla' },
    { type: 'word', content: 'nec' },
    { type: 'word', content: 'venenatis' },
    { type: 'word', content: 'gravida' },
    { type: 'comma' },
    { type: 'word', content: 'odio' },
    { type: 'word', content: 'ligula' },
    { type: 'word', content: 'mattis' },
    { type: 'word', content: 'quam' },
    { type: 'comma' },
    { type: 'word', content: 'quis' },
    { type: 'word', content: 'dictum' },
    { type: 'word', content: 'ante' },
    { type: 'word', content: 'ligula' },
    { type: 'word', content: 'at' },
    { type: 'word', content: 'ipsum' },
    { type: 'period' },
    { type: 'word', content: 'Morbi' },
    { type: 'word', content: 'tellus' },
    { type: 'word', content: 'massa' },
    { type: 'comma' },
    { type: 'word', content: 'sagittis' },
    { type: 'word', content: 'ac' },
    { type: 'word', content: 'eros' },
    { type: 'word', content: 'vitae' },
    { type: 'comma' },
    { type: 'word', content: 'ultricies' },
    { type: 'word', content: 'faucibus' },
    { type: 'word', content: 'felis' },
    { type: 'period' },
    { type: 'word', content: 'Nunc' },
    { type: 'word', content: 'mattis' },
    { type: 'word', content: 'vehicula' },
    { type: 'word', content: 'ligula' },
    { type: 'word', content: 'id' },
    { type: 'word', content: 'efficitur' },
    { type: 'period' }
  ],
  [
    { type: 'word', content: 'Aliquam' },
    { type: 'word', content: 'lacus' },
    { type: 'word', content: 'arcu' },
    { type: 'comma' },
    { type: 'word', content: 'convallis' },
    { type: 'word', content: 'placerat' },
    { type: 'word', content: 'lectus' },
    { type: 'word', content: 'pellentesque' },
    { type: 'comma' },
    { type: 'word', content: 'tincidunt' },
    { type: 'word', content: 'tincidunt' },
    { type: 'word', content: 'libero' },
    { type: 'period' },
    { type: 'word', content: 'Fusce' },
    { type: 'word', content: 'vehicula' },
    { type: 'word', content: 'ullamcorper' },
    { type: 'word', content: 'lacinia' },
    { type: 'period' },
    { type: 'word', content: 'Proin' },
    { type: 'word', content: 'id' },
    { type: 'word', content: 'orci' },
    { type: 'word', content: 'interdum' },
    { type: 'comma' },
    { type: 'word', content: 'fringilla' },
    { type: 'word', content: 'elit' },
    { type: 'word', content: 'quis' },
    { type: 'comma' },
    { type: 'word', content: 'pulvinar' },
    { type: 'word', content: 'velit' },
    { type: 'period' },
    { type: 'word', content: 'Nulla' },
    { type: 'word', content: 'efficitur' },
    { type: 'word', content: 'molestie' },
    { type: 'word', content: 'dapibus' },
    { type: 'period' },
    { type: 'word', content: 'Cras' },
    { type: 'word', content: 'aliquet' },
    { type: 'word', content: 'sapien' },
    { type: 'word', content: 'non' },
    { type: 'word', content: 'semper' },
    { type: 'word', content: 'vulputate' },
    { type: 'period' },
    { type: 'word', content: 'Cras' },
    { type: 'word', content: 'faucibus' },
    { type: 'word', content: 'aliquam' },
    { type: 'word', content: 'lacus' },
    { type: 'comma' },
    { type: 'word', content: 'sed' },
    { type: 'word', content: 'rhoncus' },
    { type: 'word', content: 'lacus' },
    { type: 'word', content: 'dignissim' },
    { type: 'word', content: 'vel' },
    { type: 'period' },
    { type: 'word', content: 'Cras' },
    { type: 'word', content: 'euismod' },
    { type: 'word', content: 'ex' },
    { type: 'word', content: 'vel' },
    { type: 'word', content: 'aliquam' },
    { type: 'word', content: 'mollis' },
    { type: 'period' },
    { type: 'word', content: 'Nam' },
    { type: 'word', content: 'dapibus' },
    { type: 'word', content: 'bibendum' },
    { type: 'word', content: 'urna' },
    { type: 'comma' },
    { type: 'word', content: 'ut' },
    { type: 'word', content: 'consequat' },
    { type: 'word', content: 'metus' },
    { type: 'word', content: 'efficitur' },
    { type: 'word', content: 'non' },
    { type: 'period' },
    { type: 'word', content: 'Aliquam' },
    { type: 'word', content: 'et' },
    { type: 'word', content: 'dignissim' },
    { type: 'word', content: 'sem' },
    { type: 'period' }
  ]
];

LoremWords.Words =
  LoremWords
    .reduce((acc, paragraph) => [...acc, ...paragraph], [])
    .filter(token => token.type === 'word')
    .map(token => token.content);

export default LoremWords;
